server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "BvL6V+G9Y7f2N6p5D9Z8x1C2v3B4n5M6q7W8e9R0t1Y2u3I4o5P6a7S8d9F0g1H2"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true