server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agms_zone_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
external:
  iot:
    base-url: "http://104.211.95.241:8080/api"
    username: "agms_prashan_7070"
    password: "Iot@Prashan123"
